apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jn8frhn6s-nodejs 
  janus-idp.io/tekton: jn8frhn6s-nodejs
  backstage.io/kubernetes-id: jn8frhn6s-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jn8frhn6s-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  