apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jn8frhn6s-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:da4a1ab24dc20d90e6da69e9d5338d8f2c334a27@sha256:a72219582b8ef2db116edc3b731de0a50b0e8fbbbdb0abc01f3e36b9def64a3d
          name: container-image
